### ISSUE TITLE
I am not able download, getting "Error in fetching the video format"

### ISSUE THREAD

**Issue by jackxyzjam** [Gotham25/hotstar-dl#5] opened 2020-01-03 18:04 UTC

**Comment by Gotham25** [comment] 2020-04-16 14:11
Hey,

Can you send me a screenshot of the URL you're trying with and error message you're receiving ?.

**Comment by Gotham25** [comment] 2020-06-14 14:48
This issue will be fixed as I merge the PR #6 
@jackxyzjam Can you test the latest binary after that ?

**Comment by jackxyzjam** [comment] 2020-06-14 16:03
Dear Gotham,

Still I am not able download video, showing error
Error in fetching the video format

Regards,
Jamal Mohamed

**Comment by Gotham25** [comment] 2020-06-14 17:58
I just deployed the latest binaries. @jackxyzjam Can you try the binaries from version 2.1.0 [here](https://github.com/Gotham25/hotstar-dl/releases/tag/v2.1.0) ?.

Let me know if you have any issues....
Also ping me the complete stack trace or screenshot of the error _with the hotstar url_ you're trying

**Comment by jackxyzjam** [comment] 2020-06-14 19:24
Dear Gotham,

Kindly help me step by step, how can download

Regards,
Jamal Mohamed
J

**Comment by jackxyzjam** [comment] 2020-06-14 19:37
This is error I am getting

[image: image.png]

**Comment by Gotham25** [comment] 2020-06-18 05:24
@jackxyzjam I have updated the README.md file. Kindly have a look at it.
[Click here](https://github.com/Gotham25/hotstar-dl) to go to the page.

Let me know if you have any doubts after that.

**Comment by jackxyzjam** [comment] 2020-06-18 16:35
Dear Gotham,

I am getting error as follows

[image: image.png]

Regards,
Jamal Mohamed

**Comment by Gotham25** [comment] 2020-06-18 16:46
@jackxyzjam I'm not able to view your image and neither can you I guess. Can you send me as text ?
Or just use any 3rd party image host site for hosting image...

Also send me the URL you're trying with. Without which I can't debug.
And the tool doesn't work on VPN. As the API's are geo-restricted

**Comment by jackxyzjam** [comment] 2020-06-18 18:51
Dear Gotham,

I am trying download url

https://www.hotstar.com/in/tv/super-singer/s-263/a-scintillating-grand-finale/1260013547


Pls  Gotham if you can able to download, download video and send to me


Regards,
Jamal Mohamed

**Comment by Gotham25** [comment] 2020-06-19 01:35
@jackxyzjam I'm able to retrieve the formats for that URL. Requesting you to run the below command and ping me the output here. 

hotstar-dl.exe -l https://www.hotstar.com/in/tv/super-singer/s-263/a-scintillating-grand-finale/1260013547

Also please run the below command and ping me the output, 

hotstar-dl.exe -v

Just to double check, let me know if you are not on VPN network. Please let me know about these three things before replying back again

**Comment by jackxyzjam** [comment] 2020-06-19 08:32
Dear Gotham,

Kindly find the information as you requested and I am running any VPN
------------------------
Version : 2.1.0
git commit SHA : 31b3508da38cc57bef1a07c98ebf88d28c361318
Built on : 2020-06-14T17:36:56Z
------------------------------------

Parsed video url is
https://www.hotstar.com/in/tv/super-singer/s-263/a-scintillating-grand-finale/1260013547

goroutine 1 [running]:
github.com/Gotham25/hotstar-dl/utils.GetDateStr(0xe8000000, 0x41d771f7,
0xd, 0x1)
        C:/Users/Gowtham/go/src/
github.com/Gotham25/hotstar-dl/utils/common.go:46 +0x327
github.com/Gotham25/hotstar-dl/utils.PopulateMetaDataMapWithMetadata(0x115e2ca0,
0x1185bb5c)
        C:/Users/Gowtham/go/src/
github.com/Gotham25/hotstar-dl/utils/playbackuri.go:71 +0x843
github.com/Gotham25/hotstar-dl/utils.GetPlaybackURI(0x11772000, 0x662c5,
0x11458120, 0x58, 0x1145816e, 0xa, 0x11505440, 0x24, 0x392d3233,
0x2d393461, ...)
        C:/Users/Gowtham/go/src/
github.com/Gotham25/hotstar-dl/utils/playbackuri.go:170 +0x3ba
github.com/Gotham25/hotstar-dl/utils.getPlayback(0x11772000, 0x662c5,
0x11458120, 0x58, 0x1145816e, 0xa, 0x11505440, 0x24, 0x4d1633, 0x6e, ...)
        C:/Users/Gowtham/go/src/
github.com/Gotham25/hotstar-dl/utils/videoutils.go:123 +0x5d
github.com/Gotham25/hotstar-dl/utils.GetVideoFormats(0x11458120, 0x58,
0x1145816e, 0xa, 0x0, 0x64, 0xaaaaaaaa, 0x68, 0x10)
        C:/Users/Gowtham/go/src/
github.com/Gotham25/hotstar-dl/utils/videoformats.go:36 +0x5ce
github.com/Gotham25/hotstar-dl/utils.ListVideoFormats(0x11458120, 0x58,
0x1145816e, 0xa, 0x0, 0x114a0000)
        C:/Users/Gowtham/go/src/
github.com/Gotham25/hotstar-dl/utils/videoformats.go:81 +0x5e
main.handleNonPlaylistURL(0x11458120, 0x58, 0x1145816e, 0xa)
        C:/Users/Gowtham/go/src/github.com/Gotham25/hotstar-dl/main.go:134
+0x6c
main.main()
        C:/Users/Gowtham/go/src/github.com/Gotham25/hotstar-dl/main.go:178
+0xd8

C:\Users\jack\Downloads\HOTSTAR\hotstar-dl_windows_386>hotstardl.exe -v
Version : 2.1.0
git commit SHA : 31b3508da38cc57bef1a07c98ebf88d28c361318
Built on : 2020-06-14T17:36:56Z

C:\Users\jack\Downloads\HOTSTAR\hotstar-dl_windows_386>

Regards,
Jamal Mohamed

**Comment by Gotham25** [comment] 2020-06-19 14:00
@jackxyzjam As I said already, the downloader **doesn't work on VPN**. As the API calls are ge-restricted and don't work on VPN networks.

Requesting you to try it on a normal network without VPN. 

Closing this as the issue is resolved.

If you further have  issues, raise a new one

**Closed as completed by Gotham25** 2020-06-19 14:00 UTC
Labels: bug
